# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sI1hX0U-eYICqEee6cnxL5I-hOeW60j5
"""

import matplotlib.pyplot as plt
import matplotlib.animation as animation
import matplotlib.patches as patches
from IPython.display import HTML
import numpy as np

# --- Configuration ---
COLOR_BANK_A = '#1f77b4'      # Blue
COLOR_BANK_B = '#ff7f0e'      # Orange
COLOR_AGGREGATOR = '#2ca02c'  # Green
COLOR_DATA = '#d62728'        # Red (Locked Data)
COLOR_WEIGHTS = '#9467bd'     # Purple (Safe Updates)

# Layout positions
POS_BANK_A = (0.2, 0.3)
POS_BANK_B = (0.8, 0.3)
POS_AGGREGATOR = (0.5, 0.8)

# Create figure
fig, ax = plt.subplots(figsize=(10, 6))
plt.subplots_adjust(bottom=0.25)

# --- Helper Functions ---
def draw_box(ax, pos, width, height, color, label):
    rect = patches.Rectangle((pos[0]-width/2, pos[1]-height/2), width, height,
                             linewidth=2, edgecolor=color, facecolor='white', zorder=2)
    ax.add_patch(rect)
    ax.text(pos[0], pos[1] + height/2 + 0.03, label,
            ha='center', va='bottom', fontsize=11, fontweight='bold', color=color)
    return rect

def draw_database(ax, pos, color):
    # cylinder-ish shape for DB
    ellipse = patches.Ellipse((pos[0], pos[1]-0.05), 0.12, 0.04, color=color, alpha=0.2, zorder=3)
    ax.add_patch(ellipse)
    ax.text(pos[0], pos[1]-0.05, "Raw DB\n(LOCKED)", ha='center', va='center', fontsize=7, color=color, zorder=4)

# --- Static Elements Setup ---
ax.set_xlim(0, 1)
ax.set_ylim(0, 1)
ax.axis('off')

# Draw Entities
draw_box(ax, POS_BANK_A, 0.2, 0.2, COLOR_BANK_A, "Bank A")
draw_box(ax, POS_BANK_B, 0.2, 0.2, COLOR_BANK_B, "Bank B")
draw_box(ax, POS_AGGREGATOR, 0.25, 0.15, COLOR_AGGREGATOR, "Aggregator")

# Draw Raw Data
draw_database(ax, POS_BANK_A, COLOR_DATA)
draw_database(ax, POS_BANK_B, COLOR_DATA)

# Dynamic Elements
status_text = ax.text(0.5, 0.55, "", ha='center', va='center', fontsize=10, style='italic')
packet_a = patches.Circle(POS_BANK_A, 0.015, color=COLOR_WEIGHTS, visible=False, zorder=5)
packet_b = patches.Circle(POS_BANK_B, 0.015, color=COLOR_WEIGHTS, visible=False, zorder=5)
ax.add_patch(packet_a)
ax.add_patch(packet_b)

# --- Accuracy Chart Setup (Inset) ---
ax_chart = plt.axes([0.35, 0.05, 0.3, 0.15]) # [left, bottom, width, height]
bars = ax_chart.bar(['Single', 'Federated'], [0, 0], color=['gray', COLOR_AGGREGATOR])
ax_chart.set_ylim(0, 100)
ax_chart.set_title("Model Accuracy %", fontsize=9)
ax_chart.tick_params(labelsize=8)

# --- Animation Logic ---
def update(frame):
    # Phase 1: Local Training (Frames 0-40)
    if frame < 40:
        status_text.set_text("1. Training Locally on Private Data\n(Raw Data stays inside Bank)")

        # Flash effect
        if frame % 10 < 5:
            # REMOVED the invalid 'tag' argument here
            ax.text(POS_BANK_A[0], POS_BANK_A[1]+0.02, "Training...", ha='center', color=COLOR_BANK_A, fontsize=8)
            ax.text(POS_BANK_B[0], POS_BANK_B[1]+0.02, "Training...", ha='center', color=COLOR_BANK_B, fontsize=8)

        bars[0].set_height(65)
        bars[1].set_height(0)

    # Phase 2: Sending Updates (Frames 40-90)
    elif frame < 90:
        status_text.set_text("2. Sending Weights (Encrypted)\nNO RAW DATA TRANSFERRED")

        packet_a.set_visible(True)
        packet_b.set_visible(True)

        progress = (frame - 40) / 50

        # Move packets
        packet_a.center = (POS_BANK_A[0] + (POS_AGGREGATOR[0] - POS_BANK_A[0]) * progress,
                           POS_BANK_A[1] + (POS_AGGREGATOR[1] - POS_BANK_A[1]) * progress)
        packet_b.center = (POS_BANK_B[0] + (POS_AGGREGATOR[0] - POS_BANK_B[0]) * progress,
                           POS_BANK_B[1] + (POS_AGGREGATOR[1] - POS_BANK_B[1]) * progress)

    # Phase 3: Aggregation (Frames 90-120)
    elif frame < 120:
        packet_a.set_visible(False)
        packet_b.set_visible(False)
        status_text.set_text("3. Aggregator creates 'Global Model v2'\n(Averaging Weights)")

        if frame % 10 < 5:
            ax.text(POS_AGGREGATOR[0], POS_AGGREGATOR[1], "MERGING", ha='center', va='center', color='white', fontweight='bold', fontsize=8)

    # Phase 4: Distribute & Improve (Frames 120-160)
    else:
        status_text.set_text("4. Global Model v2 deployed.\nAccuracy Improves!")

        # Animate chart going up
        current = bars[1].get_height()
        if current < 92:
            bars[1].set_height(current + 3)

        ax.text(POS_BANK_A[0], POS_BANK_A[1]+0.05, "v2", ha='center', color='green', fontweight='bold')
        ax.text(POS_BANK_B[0], POS_BANK_B[1]+0.05, "v2", ha='center', color='green', fontweight='bold')

    return []

# Create Animation
ani = animation.FuncAnimation(fig, update, frames=160, interval=50, blit=False)

# RENDER IN COLAB
plt.close() # Prevents the static plot from showing up
HTML(ani.to_jshtml())





